config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#show'
  get 'users/sign_in'
  post 'users/logging'
  post 'events/attend_to_event'
  get 'users/sign_out'
  post 'events/invite_to_event'
  get 'users/notifications'
  post 'users/attend_event'
  post 'users/decline_invitation'
  resources :users, only:  [:show, :new, :create, :sign_in, :logging, :sign_out, :notifications, 
    :attend_event, :decline_invitation]
  resources :events, only: [:index, :show, :new, :create, :attend_to_event, :invite_to_event]
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee
  has_many :invitations
  validates :title, :date, presence: true

  scope :upcoming_events, lambda { |user = nil|
    if user.nil?
      where(accessibility: false)
        .where(' date >= now()').order('date asc')
    else
      where(' date >= now()').order('date asc')
        .left_joins(:invitations).distinct(:id)
        .where('events.accessibility = ?
          or events.creator_id = ?
          or invitations.invitee_id = ?', false, user.id, user.id)
    end
  }

  scope :previous_events, lambda { |user = nil|
    if user.nil?
      where(accessibility: false)
        .where(' date < now()').order('date desc')
    else
      where(' date < now()').order('date desc')
        .left_joins(:invitations).distinct(:id)
        .where('events.accessibility = ?
                or events.creator_id = ?
                or invitations.invitee_id = ?', false, user.id, user.id)
    end
  }

  def attendees_members
    attendees.order('attendances.created_at desc')
  end

  def add_new_attendee(user)
    attendees.push(user)
    if_invitation_update(user)
  rescue ActiveRecord::RecordNotUnique
    errors.add(:attendees, :register_already, message: " #{user.username} you are already attending this event!")
  end

  def self.add_new_invitation(event, invitee_id)
    invitation = Invitation.new
    invitation.host_id = event.creator_id
    invitation.event_id = event.id
    invitation.invitee_id = invitee_id
    invitation.status = 'pending'
    invitation.save
  end

  def user_in_invited_list?(user_id)
    invited = invitations.where(invitee_id: user_id).first
    invited.nil? ? false : true
  end

  def change_status_to_declined(invitee_id)
    invitation = Invitation.where(event_id: id, invitee_id: invitee_id).first
    invitation&.update(status: 'declined')
  end

  private

  def if_invitation_update(user)
    invitation = Invitation.where(event_id: id, invitee_id: user.id).first
    invitation&.update(status: 'accepted')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  include ApplicationHelper

  def index
    @events = Event.all
    @upcoming = current_user.nil? ? Event.upcoming_events : Event.upcoming_events(current_user)
    @previous = current_user.nil? ? Event.previous_events : Event.previous_events(current_user)
  end

  def show
    @event = Event.find(params[:id])
    redirect_to root_path unless can_see_event?
    @attendees_members = @event.attendees_members
    @uninvited_people = User.uninvited_users(@event)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.date = fill_event_date(@event)
    if @event.save
      redirect_to current_user
    else
      flash[:error] = @event.errors.full_messages
      render :new
    end
  end

  def attend_to_event
    if current_user.nil?
      flash[:error] = ['You need to sign in or sign up to register to this event']
      visited_event_set(params[:event][:id])
      redirect_to users_sign_in_path
    else
      @event = Event.find(params[:event][:id])
      register_to_event(@event)
      flash[:error] = @event.errors.full_messages if @event.errors.any?
      redirect_to @event
    end
  end

  def invite_to_event
    @event = Event.find(params[:event])
    invitee_id = params[:invitee].to_i
    if Event.add_new_invitation(@event, invitee_id)
      redirect_to @event
    else
      render :show
    end
  end

  private

  def fill_event_date(event)
    return nil if event.date.nil?

    DateTime.new(event.date.year,
                 event.date.month,
                 event.date.day,
                 params[:date_time].to_s.split(':')[0].to_i,
                 params[:date_time].to_s.split(':')[1].to_i, 0)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:date, :description, :title, :location, :accessibility)
  end

  def attendees?
    @event.attendees.count.positive? ? 'Attendees: ' : 'This event has not attendees yet'
  end

  def upcoming_events?
    @upcoming.count.positive? ? 'Upcoming Events:' : 'No upcoming events yet'
  end

  def previous_events?
    @previous.count.positive? ? 'Previous Events:' : 'No previous events'
  end

  def public_event?
    @event.accessibility ? 'Public' : 'Private'
  end

  def can_see_event?
    if current_user.nil?
      false
    elsif current_user.id == @event.creator_id ||
          @event.user_in_invited_list?(current_user.id)
      true
    end
  end
end

app/views/events/_previous.html.erb
<h3><%= previous_events? %></h3>
<ul>
  <% @previous.each do |event| %>
    <li>
    <%= link_to  event.title, event_path(event) %>
    <span><%= event.date.strftime("Event's day was on %m/%d/%Y at %H:%M") %></span>
    </li>
  <% end %>
</ul>

app/views/events/_upcoming.html.erb
<h3><%= upcoming_events? %></h3>
<ul>
  <% @upcoming.each do |event| %>
    <li>
    <%= link_to  event.title, event_path(event) %>
    <span><%= event.date.strftime("Event's day on %m/%d/%Y at %H:%M") %></span>
    </li>
  <% end %>
</ul>

app/views/events/index.html.erb
<h1>List of events</h1>
<%= render 'upcoming'%>
<%= render 'previous'%>

app/views/events/new.html.erb
<h1>Create a new Event</h1>

<%= form_for @event do |f| %>
   <%= f.text_field :title %><br>
   <%= f.label :description, value: 'Event description: '%>
   <%= f.text_field :description %><br>
   <%= f.label :location, value: 'Location: '%>
   <%= f.text_field :location %><br>
   <%= f.label :date, value: 'Date: ' %>
   <%= f.date_field :date, min: Date.new(2000, 01, 01), max:Date.new(2050, 12, 31) %><br>
   <%= label_tag 'Time: ' %>
   <%= time_field_tag 'date_time' %><br>
   <%= f.label :accessibility, value: 'Make this event private: '%>
   <%= f.check_box :accessibility %><br><br>
   <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.title%> </h1>
<b>Description:</b><h2><%= @event.description %></h2>
<p>Date:<%=@event.date%></p>
<p>Location: <%= @event.location %></p>
<h4>Created by: <%=link_to @event.creator.username, @event.creator %></h4>

<%= form_for(@event, url: events_attend_to_event_url, method: :post  ) do |f| %>
  <%= f.hidden_field :id %>
  <%= f.submit "Attend" %>
<% end %>

<h3>
<%= have_attendees? %>
</h3>

<ul>
  <% @attendees_members.each do |attendee| %>
    <li>
      <%=link_to attendee.username, user_path(attendee) %>
    </li>
  <% end %>
</ul>
<%if current_user.id == @event.creator.id %>
  <h4>People to invite</h4>
  <ul>
  <% @uninvited_people.each do |user| %>
    <li>
    <%= link_to user.username + '\'s profile', user_path(user) %> 
      <%= link_to 'invite', events_invite_to_event_path(event: @event.id, invitee: user.id ),
          method: :invite_to_event, data: {confirm: "Invite #{user.username}?"} %>    </li>
  <% end %>
  </ul>
<% end %>