config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#show'
  get 'users/sign_in'
  post 'users/logging'
  post 'events/attend_to_event'
  get 'users/sign_out'
  post 'events/invite_to_event'
  get 'users/notifications'
  post 'users/attend_event'
  post 'users/decline_invitation'
  resources :users, only:  [:show, :new, :create, :sign_in, :logging, :sign_out, :notifications, 
    :attend_event, :decline_invitation]
  resources :events, only: [:index, :show, :new, :create, :attend_to_event, :invite_to_event]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to 'Home', root_path%>
  <% if session[:user].nil? %>
  <%= link_to 'Sign in', users_sign_in_path%>
  <%= link_to 'Sign up', new_user_path%>
  <% else %>
  <%= link_to 'Sign out', users_sign_out_path %>
  <%= link_to current_user.username, current_user %>
  <%= link_to 'Create a new event', new_event_path %>
  <%= link_to  "Notifications (#{user_pending_invitations(current_user.id)})", users_notifications_path %>
  <% end %>
  <% if !flash[:error].nil? %>
  <div id="error_explanation">
    <strong><%= flash[:error] %></strong>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>